"""empty message

Revision ID: 1349e734c226
Revises: 18ed84a589a2
Create Date: 2020-07-07 23:43:49.509835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1349e734c226'
down_revision = '18ed84a589a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('likes_count', sa.Integer(), nullable=False))
    op.drop_column('product', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('product', 'likes_count')
    # ### end Alembic commands ###
