"""empty message

Revision ID: 3488bee76e12
Revises: cda5cf90bd17
Create Date: 2020-07-08 00:05:05.816413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3488bee76e12'
down_revision = 'cda5cf90bd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('like', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'like', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'like', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_column('like', 'user_id')
    op.drop_column('like', 'product_id')
    # ### end Alembic commands ###
