"""empty message

Revision ID: 38575fce3af4
Revises: 6933aa630d32
Create Date: 2020-06-08 00:22:14.108327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38575fce3af4'
down_revision = '6933aa630d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('departamento', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'departamento')
    # ### end Alembic commands ###
