"""Profile picture added

Revision ID: 6933aa630d32
Revises: f9b15d8b76df
Create Date: 2020-06-07 22:24:23.382220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6933aa630d32'
down_revision = 'f9b15d8b76df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('background_picture', sa.String(), nullable=True))
    op.add_column('store', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'profile_picture')
    op.drop_column('store', 'background_picture')
    # ### end Alembic commands ###
