"""empty message

Revision ID: cda5cf90bd17
Revises: 1349e734c226
Create Date: 2020-07-07 23:56:15.940277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda5cf90bd17'
down_revision = '1349e734c226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_product_id_fkey', 'like', type_='foreignkey')
    op.drop_constraint('like_user_id_fkey', 'like', type_='foreignkey')
    op.drop_column('like', 'product_id')
    op.drop_column('like', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('like', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('like_user_id_fkey', 'like', 'user', ['user_id'], ['id'])
    op.create_foreign_key('like_product_id_fkey', 'like', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
